pipeline {
    agent any

    environment {
        IMAGE_NAME = "casepilot"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Give Permission') {
            steps {
                sh 'chmod +x gradlew'
            }
        }

        stage('Build Project') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:latest .'
            }
        }

    }

    post {
        success {
            echo "Build Successful!"
        }

        failure {
            echo "Build Failed!"
        }
    }
}